FROM python:3.12-alpine@sha256:6d43704baacd1bfbe7c295d7f13079d5d8104ed33568873133f8fc69980419df

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PIP_NO_CACHE_DIR=1 \
    DJANGO_SETTINGS_MODULE=config.settings.test

RUN addgroup -S pamolive && adduser -S -G pamolive -h /home/pamolive pamolive
WORKDIR /app

COPY requirements-dev.lock ./
RUN pip install --require-hashes -r requirements-dev.lock

COPY pyproject.toml README.md ./
COPY pamolive ./pamolive
COPY config ./config
COPY keyring ./keyring
COPY manage.py ./
COPY compose.yml Dockerfile Dockerfile.guacamole requirements.lock ./
COPY deploy ./deploy
COPY templates ./templates
COPY static ./static
COPY tests ./tests

RUN chown -R pamolive:pamolive /app

USER pamolive
CMD ["pytest", "--cov=pamolive", "--cov-fail-under=90", "-q"]
