# Generated by Django 5.2.16 on 2026-07-13 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('approvals', '0001_initial'),
        ('policies', '0001_initial'),
        ('targets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='accessrequest',
            name='policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='policies.accesspolicy'),
        ),
        migrations.AddField(
            model_name='accessrequest',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='access_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accessrequest',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='targets.target'),
        ),
    ]
