# Generated by Django 5.2.16 on 2026-07-13 14:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('targets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('username', models.CharField(max_length=255)),
                ('kind', models.CharField(choices=[('password', 'Password'), ('ssh_key', 'SSH private key')], max_length=20)),
                ('encrypted_secret', models.BinaryField()),
                ('key_version', models.PositiveIntegerField(default=1)),
                ('last_rotated_at', models.DateTimeField(blank=True, null=True)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='targets.target')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
