# Generated by Django 5.2.16 on 2026-07-13 19:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0003_accessrequest_ticket_reference_approvaldecision'),
        ('policies', '0004_accesspolicy_approval_quorum_and_more'),
        ('privileged_sessions', '0001_initial'),
        ('vault', '0005_secretlease'),
    ]

    operations = [
        migrations.AddField(
            model_name='privilegedsession',
            name='credential',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='privileged_sessions', to='vault.credential'),
        ),
        migrations.AddField(
            model_name='privilegedsession',
            name='expires_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='privilegedsession',
            name='last_activity_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='privilegedsession',
            name='policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='privileged_sessions', to='policies.accesspolicy'),
        ),
        migrations.AddField(
            model_name='privilegedsession',
            name='termination_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='privilegedsession',
            name='access_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='approvals.accessrequest'),
        ),
        migrations.CreateModel(
            name='SessionTicket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='ticket', to='privileged_sessions.privilegedsession')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
