# Generated by Django 5.2.16 on 2026-07-13 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0002_initial'),
        ('rbac', '0002_usergroup'),
        ('targets', '0002_targetgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesspolicy',
            name='actions',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='accesspolicy',
            name='target_groups',
            field=models.ManyToManyField(related_name='policies', to='targets.targetgroup'),
        ),
        migrations.AddField(
            model_name='accesspolicy',
            name='user_groups',
            field=models.ManyToManyField(related_name='policies', to='rbac.usergroup'),
        ),
        migrations.AlterField(
            model_name='accesspolicy',
            name='targets',
            field=models.ManyToManyField(blank=True, related_name='policies', to='targets.target'),
        ),
    ]
