# Generated by Django 5.2.16 on 2026-07-13 19:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0003_accesspolicy_actions_accesspolicy_target_groups_and_more'),
        ('rbac', '0006_expand_system_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesspolicy',
            name='approval_quorum',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='accesspolicy',
            name='approver_groups',
            field=models.ManyToManyField(blank=True, related_name='approval_policies', to='rbac.usergroup'),
        ),
        migrations.AddField(
            model_name='accesspolicy',
            name='ticket_required',
            field=models.BooleanField(default=False),
        ),
    ]
