# Generated by Django 5.2.16 on 2026-07-13 20:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('privileged_sessions', '0002_privilegedsession_credential_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='privilegedsession',
            name='termination_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='privilegedsession',
            name='termination_requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='terminated_privileged_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='privilegedsession',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('active', 'Active'), ('terminating', 'Termination requested'), ('closed', 'Closed'), ('failed', 'Failed')], default='created', max_length=20),
        ),
    ]
