# Generated by Django 5.2.16 on 2026-07-13 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0002_usergroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='capabilities',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='role',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='role',
            name='is_system',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='role',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='usergroup',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='user_groups', to='rbac.role'),
        ),
    ]
