TRANSLATIONS = {
    "fr": {
        "home": "Accueil",
        "passwords": "Mots de passe",
        "targets": "Cibles",
        "administration": "Administration",
        "my_account": "Mon compte",
        "logout": "Se d?connecter",
        "theme": "Changer de th?me",
        "theme_system": "Auto",
        "theme_light": "Clair",
        "theme_dark": "Sombre",
        "language": "Langue",
        "personal_space": "Espace personnel",
        "hello": "Bonjour",
        "home_intro": (
            "Retrouvez rapidement vos coffres et les environnements auxquels vous avez acc?s."
        ),
        "platform_ok": "Plateforme op?rationnelle",
        "vault_audit_available": "Coffre et audit disponibles",
        "requests": "Demandes",
        "pending": "en attente",
        "access": "Acc?s",
        "my_target_groups": "Mes groupes de cibles",
        "view_all": "Tout afficher",
        "activity": "Activit?",
        "in_progress": "En cours",
        "no_group": "Aucun groupe accessible",
        "no_group_help": "Une politique doit relier l?un de vos groupes ? un groupe de cibles.",
        "encrypted_vaults": "Coffres chiffr?s",
        "password_page_title": "Mots de passe.",
        "password_page_intro": "Vos secrets personnels et les identifiants des cibles autoris?es.",
        "add_secret": "Ajouter un secret",
        "create_group": "Cr?er un groupe",
        "save_vault": "Enregistrer dans mon coffre",
        "save_group": "Cr?er le groupe",
        "personal": "Personnel",
        "my_vault": "Mon coffre",
        "private_items": "Ces ?l?ments ne sont visibles que par vous.",
        "ungrouped": "Sans groupe",
        "empty_vault": "Votre coffre est vide",
        "empty_vault_help": "Ajoutez un mot de passe, un TOTP, une carte ou une note s?curis?e.",
        "reveal_audit": "Afficher et auditer",
        "business_justification": "Justification m?tier",
        "session_reason_placeholder": "Pourquoi cette session est-elle n?cessaire ?",
        "reveal_reason_placeholder": "Pourquoi devez-vous consulter ce secret ?",
        "access_denied": "Acc?s refus?",
        "edit": "Modifier",
        "authorized_credentials": "Identifiants autoris?s",
        "authorized_credentials_help": "Leur visibilit? d?pend de vos groupes et politiques.",
        "no_target_credentials": "Aucun identifiant de cible autoris?",
        "no_target_credentials_help": "Une politique doit autoriser l?action Consulter un secret.",
        "account_title": "Mon compte.",
        "account_intro": (
            "Modifiez votre profil, vos pr?f?rences, votre mot de passe et la protection MFA."
        ),
        "preferences": "Pr?f?rences",
        "appearance_language": "Apparence et langue",
        "save_preferences": "Enregistrer les pr?f?rences",
        "admin_overview": "Vue d?ensemble",
        "identities_rights": "Identit?s et droits",
        "users": "Utilisateurs",
        "user_groups": "Groupes utilisateurs",
        "roles_permissions": "R?les et permissions",
        "ldap_directories": "Annuaires LDAP / AD",
        "oidc_providers": "Domaines de connexion",
        "group_mappings": "Correspondances de groupes",
        "target_groups": "Groupes de cibles",
        "ssh_rdp_equipment": "?quipements SSH / RDP",
        "domains": "Domaines",
        "ssh_host_keys": "Cl?s d?h?te SSH",
        "password_management": "Gestion des mots de passe",
        "target_credentials": "Identifiants des cibles",
        "rotation_policies": "Politiques de rotation",
        "rotations": "Rotations",
        "authorizations": "Autorisations",
        "access_policies": "Politiques d?acc?s",
        "time_frames": "Plages horaires",
        "current_approvals": "Approbations en cours",
        "monitoring_audit": "Surveillance et audit",
        "sessions": "Sessions",
        "audit_log": "Journal d?audit",
        "technical_admin": "Administration technique",
        "system": "Syst?me",
        "session_policy": "Politique de session",
        "session_policy_intro": (
            "D?connectez automatiquement les sessions web inactives ou trop anciennes."
        ),
        "enforced": "Appliqu?e c?t? serveur",
        "browser_sessions": "Sessions navigateur",
        "inactivity_and_absolute": "Inactivit? et dur?e absolue",
        "save_policy": "Enregistrer la politique",
        "mfa_required_enabled": "MFA obligatoire activ?e",
        "mfa_required_enabled_detail": (
            "Tout utilisateur interactif doit confirmer un TOTP avant d?acc?der aux "
            "secrets ou aux sessions privil?gi?es."
        ),
        "mfa_required_disabled": "Avertissement : MFA globale d?sactiv?e",
        "mfa_required_disabled_detail": (
            "Les comptes sans second facteur peuvent acc?der ? PAM-olive. Cette "
            "configuration r?duit fortement la protection de la plateforme."
        ),
        "enforcement": "Application",
        "server_side_control": "Contr?le ind?pendant du navigateur",
        "session_policy_detail": (
            "Le d?lai est contr?l? sur chaque requ?te authentifi?e. Fermer JavaScript ou "
            "modifier l?horloge du navigateur ne d?sactive pas la r?gle."
        ),
        "idle_limit": "D?lai maximal sans activit?",
        "absolute_limit": "Nouvelle authentification obligatoire",
        "control_title": "Pilotez PAM-olive.",
        "control_intro": (
            "Identit?s, mots de passe, cibles, approbations et tra?abilit? depuis une "
            "console unique."
        ),
        "connected_users": "Utilisateurs connect?s",
        "active_sessions": "Sessions actives",
        "failed_logins": "?checs de connexion (24 h)",
        "pending_approvals": "? approuver",
        "system_state": "?tat du syst?me",
        "recent_failures": "?checs r?cents",
        "database": "Base de donn?es",
        "cache": "Cache",
        "operational": "Op?rationnel",
        "no_recent_failure": "Aucun ?chec r?cent",
        "governed_console": "Console gouvern?e",
        "groups_without_policy": "groupes sans politique",
        "groups_without_policy_help": "Ces groupes ne donnent encore aucun acc?s.",
        "targets_without_credential": "cibles sans identifiant",
        "targets_without_credential_help": (
            "Chaque cible devrait disposer d?au moins un identifiant."
        ),
        "configure": "Configurer",
        "fix": "Corriger",
        "web_sessions": "Sessions web",
        "authentication": "Authentification",
        "awaiting_decision": "En attente d?une d?cision",
        "live": "Temps r?el",
        "now": "Maintenant",
        "error": "Erreur",
        "events_24h": "?v?nements / 24 h",
        "security": "S?curit?",
        "multiple_groups_explicit_rights": "Groupes multiples, droits explicites",
        "deny_by_default": "Refus par d?faut",
        "multi_group_help": "Un utilisateur peut appartenir ? plusieurs groupes.",
        "capability_help": "Fonctions PAM et acc?s aux cibles.",
        "authorized_scopes_help": "Uniquement les p?rim?tres autoris?s.",
        "unknown": "Inconnu",
        "target_scopes": "P?rim?tres autoris?s",
        "targets_page_title": "Cibles.",
        "targets_page_intro": (
            "Seuls les groupes de cibles accord?s par vos politiques sont affich?s."
        ),
        "my_requests": "Mes demandes",
        "authorized_target_group": "Groupe de cibles autoris?",
        "target_singular": "cible",
        "credential_singular": "identifiant",
        "open_session": "Ouvrir",
        "no_account": "Aucun compte",
        "request": "Demander",
        "read_only": "Consultation seule",
        "empty_target_group": "Ce groupe ne contient encore aucune cible.",
        "no_target_group": "Aucun groupe de cibles accessible",
        "no_target_group_help": (
            "Vous ne verrez ici que les groupes explicitement autoris?s par une "
            "politique active."
        ),
        "view_requests": "Voir mes demandes",
        "privileged_access": "Acc?s privil?gi?s",
        "requests_title": "Mes demandes.",
        "requests_intro": "Demandez un acc?s couvert par les politiques de vos groupes.",
        "new_request": "Nouvelle demande",
        "justify_need": "Justifiez votre besoin",
        "send_request": "Envoyer la demande",
        "no_policy": "Aucune politique disponible",
        "no_policy_help": (
            "Votre groupe doit recevoir une politique autorisant les demandes d?acc?s."
        ),
        "history": "Historique",
        "request_singular": "demande",
        "no_request": "Aucune demande",
        "request_history_help": "Votre historique appara?tra ici.",
        "profile": "Profil",
        "personal_information": "Informations personnelles",
        "save_profile": "Enregistrer le profil",
        "account_security": "S?curit?",
        "change_password": "Changer le mot de passe",
        "save_password": "Modifier le mot de passe",
        "totp_authentication": "Authentification TOTP",
        "mfa_enabled": "MFA activ?e",
        "mfa_enabled_help": (
            "Un code TOTP ou un code de r?cup?ration est demand? ? chaque connexion."
        ),
        "last_use": "Derni?re utilisation",
        "never": "Jamais",
        "recovery_codes": "codes disponibles",
        "renew_recovery": "Renouveler les codes de r?cup?ration",
        "generate_recovery": "G?n?rer de nouveaux codes",
        "reset_mfa": "R?initialiser la MFA",
        "reset_mfa_help": "L?appareil TOTP et tous les codes de r?cup?ration seront invalid?s.",
        "disable_mfa": "D?sactiver la MFA",
        "mfa_setup_help": "Ajoutez une seconde protection avec votre application TOTP locale.",
        "configure_totp": "Configurer le TOTP",
    },
    "en": {
        "home": "Home",
        "passwords": "Passwords",
        "targets": "Targets",
        "administration": "Administration",
        "my_account": "My account",
        "logout": "Sign out",
        "theme": "Switch theme",
        "theme_system": "Auto",
        "theme_light": "Light",
        "theme_dark": "Dark",
        "language": "Language",
        "personal_space": "Personal workspace",
        "hello": "Hello",
        "home_intro": "Quickly access your vaults and authorized environments.",
        "platform_ok": "Platform operational",
        "vault_audit_available": "Vault and audit available",
        "requests": "Requests",
        "pending": "pending",
        "access": "Access",
        "my_target_groups": "My target groups",
        "view_all": "View all",
        "activity": "Activity",
        "in_progress": "In progress",
        "no_group": "No accessible group",
        "no_group_help": "A policy must link one of your groups to a target group.",
        "encrypted_vaults": "Encrypted vaults",
        "password_page_title": "Passwords.",
        "password_page_intro": "Your personal secrets and authorized target credentials.",
        "add_secret": "Add a secret",
        "create_group": "Create a group",
        "save_vault": "Save to my vault",
        "save_group": "Create group",
        "personal": "Personal",
        "my_vault": "My vault",
        "private_items": "Only you can see these items.",
        "ungrouped": "Ungrouped",
        "empty_vault": "Your vault is empty",
        "empty_vault_help": "Add a password, TOTP, payment card, or secure note.",
        "reveal_audit": "Reveal and audit",
        "business_justification": "Business justification",
        "session_reason_placeholder": "Why is this session necessary?",
        "reveal_reason_placeholder": "Why do you need to reveal this secret?",
        "access_denied": "Access denied",
        "edit": "Edit",
        "authorized_credentials": "Authorized credentials",
        "authorized_credentials_help": "Visibility depends on your groups and policies.",
        "no_target_credentials": "No authorized target credentials",
        "no_target_credentials_help": "A policy must allow the View secret action.",
        "account_title": "My account.",
        "account_intro": "Update your profile, preferences, password, and MFA protection.",
        "preferences": "Preferences",
        "appearance_language": "Appearance and language",
        "save_preferences": "Save preferences",
        "admin_overview": "Overview",
        "identities_rights": "Identities and access",
        "users": "Users",
        "user_groups": "User groups",
        "roles_permissions": "Roles and permissions",
        "ldap_directories": "LDAP / AD directories",
        "oidc_providers": "Login domains",
        "group_mappings": "Group mappings",
        "target_groups": "Target groups",
        "ssh_rdp_equipment": "SSH / RDP equipment",
        "domains": "Domains",
        "ssh_host_keys": "SSH host keys",
        "password_management": "Password management",
        "target_credentials": "Target credentials",
        "rotation_policies": "Rotation policies",
        "rotations": "Rotations",
        "authorizations": "Authorizations",
        "access_policies": "Access policies",
        "time_frames": "Time frames",
        "current_approvals": "Pending approvals",
        "monitoring_audit": "Monitoring and audit",
        "sessions": "Sessions",
        "audit_log": "Audit log",
        "technical_admin": "Technical administration",
        "system": "System",
        "session_policy": "Session policy",
        "session_policy_intro": "Automatically disconnect inactive or overly old web sessions.",
        "enforced": "Server-side enforced",
        "browser_sessions": "Browser sessions",
        "inactivity_and_absolute": "Idle and absolute duration",
        "save_policy": "Save policy",
        "mfa_required_enabled": "Mandatory MFA enabled",
        "mfa_required_enabled_detail": (
            "Every interactive user must confirm a TOTP before accessing secrets or "
            "privileged sessions."
        ),
        "mfa_required_disabled": "Warning: global MFA disabled",
        "mfa_required_disabled_detail": (
            "Accounts without a second factor can access PAM-olive. This setting "
            "significantly weakens platform protection."
        ),
        "enforcement": "Enforcement",
        "server_side_control": "Browser-independent control",
        "session_policy_detail": (
            "The timeout is checked on every authenticated request. Disabling JavaScript or "
            "changing the browser clock cannot bypass it."
        ),
        "idle_limit": "Maximum idle period",
        "absolute_limit": "New authentication required",
        "control_title": "Control PAM-olive.",
        "control_intro": (
            "Manage identities, passwords, targets, approvals, and traceability from one "
            "console."
        ),
        "connected_users": "Connected users",
        "active_sessions": "Active sessions",
        "failed_logins": "Failed logins (24h)",
        "pending_approvals": "Pending approvals",
        "system_state": "System status",
        "recent_failures": "Recent failures",
        "database": "Database",
        "cache": "Cache",
        "operational": "Operational",
        "no_recent_failure": "No recent failure",
        "governed_console": "Governed console",
        "groups_without_policy": "groups without a policy",
        "groups_without_policy_help": "These groups do not grant access yet.",
        "targets_without_credential": "targets without a credential",
        "targets_without_credential_help": "Every target should have at least one credential.",
        "configure": "Configure",
        "fix": "Fix",
        "web_sessions": "Web sessions",
        "authentication": "Authentication",
        "awaiting_decision": "Awaiting a decision",
        "live": "Live",
        "now": "Now",
        "error": "Error",
        "events_24h": "events / 24h",
        "security": "Security",
        "multiple_groups_explicit_rights": "Multiple groups, explicit permissions",
        "deny_by_default": "Deny by default",
        "multi_group_help": "A user may belong to several groups.",
        "capability_help": "PAM capabilities and target access.",
        "authorized_scopes_help": "Only authorized scopes.",
        "unknown": "Unknown",
        "target_scopes": "Authorized scopes",
        "targets_page_title": "Targets.",
        "targets_page_intro": "Only target groups granted by your policies are displayed.",
        "my_requests": "My requests",
        "authorized_target_group": "Authorized target group",
        "target_singular": "target",
        "credential_singular": "credential",
        "open_session": "Open",
        "no_account": "No account",
        "request": "Request",
        "read_only": "Read only",
        "empty_target_group": "This group does not contain any target yet.",
        "no_target_group": "No accessible target group",
        "no_target_group_help": (
            "Only groups explicitly granted by an active policy are shown here."
        ),
        "view_requests": "View my requests",
        "privileged_access": "Privileged access",
        "requests_title": "My requests.",
        "requests_intro": "Request access covered by your groups? policies.",
        "new_request": "New request",
        "justify_need": "Explain your need",
        "send_request": "Send request",
        "no_policy": "No policy available",
        "no_policy_help": "Your group must receive a policy allowing access requests.",
        "history": "History",
        "request_singular": "request",
        "no_request": "No request",
        "request_history_help": "Your history will appear here.",
        "profile": "Profile",
        "personal_information": "Personal information",
        "save_profile": "Save profile",
        "account_security": "Security",
        "change_password": "Change password",
        "save_password": "Update password",
        "totp_authentication": "TOTP authentication",
        "mfa_enabled": "MFA enabled",
        "mfa_enabled_help": "A TOTP or recovery code is required at each sign-in.",
        "last_use": "Last use",
        "never": "Never",
        "recovery_codes": "recovery codes available",
        "renew_recovery": "Renew recovery codes",
        "generate_recovery": "Generate new codes",
        "reset_mfa": "Reset MFA",
        "reset_mfa_help": "The TOTP device and all recovery codes will be invalidated.",
        "disable_mfa": "Disable MFA",
        "mfa_setup_help": "Add a second layer of protection with your local TOTP app.",
        "configure_totp": "Configure TOTP",
    },
    "es": {
        "home": "Inicio",
        "passwords": "Contrase?as",
        "targets": "Destinos",
        "administration": "Administraci?n",
        "my_account": "Mi cuenta",
        "logout": "Cerrar sesi?n",
        "theme": "Cambiar tema",
        "theme_system": "Auto",
        "theme_light": "Claro",
        "theme_dark": "Oscuro",
        "language": "Idioma",
        "personal_space": "Espacio personal",
        "hello": "Hola",
        "home_intro": "Accede r?pidamente a tus b?vedas y entornos autorizados.",
        "platform_ok": "Plataforma operativa",
        "vault_audit_available": "B?veda y auditor?a disponibles",
        "requests": "Solicitudes",
        "pending": "pendientes",
        "access": "Acceso",
        "my_target_groups": "Mis grupos de destinos",
        "view_all": "Ver todo",
        "activity": "Actividad",
        "in_progress": "En curso",
        "no_group": "Ning?n grupo accesible",
        "no_group_help": "Una pol?tica debe vincular uno de tus grupos con un grupo de destinos.",
        "encrypted_vaults": "B?vedas cifradas",
        "password_page_title": "Contrase?as.",
        "password_page_intro": "Tus secretos personales y credenciales de destino autorizadas.",
        "add_secret": "A?adir un secreto",
        "create_group": "Crear un grupo",
        "save_vault": "Guardar en mi b?veda",
        "save_group": "Crear grupo",
        "personal": "Personal",
        "my_vault": "Mi b?veda",
        "private_items": "Solo t? puedes ver estos elementos.",
        "ungrouped": "Sin grupo",
        "empty_vault": "Tu b?veda est? vac?a",
        "empty_vault_help": "A?ade una contrase?a, TOTP, tarjeta o nota segura.",
        "reveal_audit": "Mostrar y auditar",
        "business_justification": "Justificaci?n empresarial",
        "session_reason_placeholder": "?Por qu? es necesaria esta sesi?n?",
        "reveal_reason_placeholder": "?Por qu? necesita consultar este secreto?",
        "access_denied": "Acceso denegado",
        "edit": "Editar",
        "authorized_credentials": "Credenciales autorizadas",
        "authorized_credentials_help": "La visibilidad depende de tus grupos y pol?ticas.",
        "no_target_credentials": "No hay credenciales de destino autorizadas",
        "no_target_credentials_help": "Una pol?tica debe permitir la acci?n Ver secreto.",
        "account_title": "Mi cuenta.",
        "account_intro": "Actualiza tu perfil, preferencias, contrase?a y protecci?n MFA.",
        "preferences": "Preferencias",
        "appearance_language": "Apariencia e idioma",
        "save_preferences": "Guardar preferencias",
        "admin_overview": "Resumen",
        "identities_rights": "Identidades y accesos",
        "users": "Usuarios",
        "user_groups": "Grupos de usuarios",
        "roles_permissions": "Roles y permisos",
        "ldap_directories": "Directorios LDAP / AD",
        "oidc_providers": "Dominios de conexi?n",
        "group_mappings": "Mapeos de grupos",
        "target_groups": "Grupos de destinos",
        "ssh_rdp_equipment": "Equipos SSH / RDP",
        "domains": "Dominios",
        "ssh_host_keys": "Claves de host SSH",
        "password_management": "Gesti?n de contrase?as",
        "target_credentials": "Credenciales de destino",
        "rotation_policies": "Pol?ticas de rotaci?n",
        "rotations": "Rotaciones",
        "authorizations": "Autorizaciones",
        "access_policies": "Pol?ticas de acceso",
        "time_frames": "Franjas horarias",
        "current_approvals": "Aprobaciones pendientes",
        "monitoring_audit": "Supervisi?n y auditor?a",
        "sessions": "Sesiones",
        "audit_log": "Registro de auditor?a",
        "technical_admin": "Administraci?n t?cnica",
        "system": "Sistema",
        "session_policy": "Pol?tica de sesi?n",
        "session_policy_intro": (
            "Desconecta autom?ticamente las sesiones web inactivas o demasiado antiguas."
        ),
        "enforced": "Aplicada en el servidor",
        "browser_sessions": "Sesiones del navegador",
        "inactivity_and_absolute": "Inactividad y duraci?n absoluta",
        "save_policy": "Guardar pol?tica",
        "mfa_required_enabled": "MFA obligatoria activada",
        "mfa_required_enabled_detail": (
            "Cada usuario interactivo debe confirmar un TOTP antes de acceder a secretos "
            "o sesiones privilegiadas."
        ),
        "mfa_required_disabled": "Advertencia: MFA global desactivada",
        "mfa_required_disabled_detail": (
            "Las cuentas sin segundo factor pueden acceder a PAM-olive. Esta configuraci?n "
            "reduce considerablemente la protecci?n de la plataforma."
        ),
        "enforcement": "Aplicaci?n",
        "server_side_control": "Control independiente del navegador",
        "session_policy_detail": (
            "El tiempo se verifica en cada solicitud autenticada. Desactivar JavaScript o "
            "cambiar el reloj del navegador no permite evitarlo."
        ),
        "idle_limit": "Periodo m?ximo de inactividad",
        "absolute_limit": "Nueva autenticaci?n obligatoria",
        "control_title": "Controla PAM-olive.",
        "control_intro": (
            "Gestiona identidades, contrase?as, destinos, aprobaciones y trazabilidad desde "
            "una consola."
        ),
        "connected_users": "Usuarios conectados",
        "active_sessions": "Sesiones activas",
        "failed_logins": "Inicios fallidos (24 h)",
        "pending_approvals": "Aprobaciones pendientes",
        "system_state": "Estado del sistema",
        "recent_failures": "Fallos recientes",
        "database": "Base de datos",
        "cache": "Cach?",
        "operational": "Operativo",
        "no_recent_failure": "Ning?n fallo reciente",
        "governed_console": "Consola gobernada",
        "groups_without_policy": "grupos sin pol?tica",
        "groups_without_policy_help": "Estos grupos todav?a no conceden acceso.",
        "targets_without_credential": "destinos sin credenciales",
        "targets_without_credential_help": "Cada destino deber?a tener al menos una credencial.",
        "configure": "Configurar",
        "fix": "Corregir",
        "web_sessions": "Sesiones web",
        "authentication": "Autenticaci?n",
        "awaiting_decision": "Esperando una decisi?n",
        "live": "En directo",
        "now": "Ahora",
        "error": "Error",
        "events_24h": "eventos / 24 h",
        "security": "Seguridad",
        "multiple_groups_explicit_rights": "M?ltiples grupos, permisos expl?citos",
        "deny_by_default": "Denegar por defecto",
        "multi_group_help": "Un usuario puede pertenecer a varios grupos.",
        "capability_help": "Funciones PAM y acceso a destinos.",
        "authorized_scopes_help": "Solo ?mbitos autorizados.",
        "unknown": "Desconocido",
        "target_scopes": "?mbitos autorizados",
        "targets_page_title": "Destinos.",
        "targets_page_intro": (
            "Solo se muestran los grupos de destinos concedidos por tus pol?ticas."
        ),
        "my_requests": "Mis solicitudes",
        "authorized_target_group": "Grupo de destinos autorizado",
        "target_singular": "destino",
        "credential_singular": "credencial",
        "open_session": "Abrir",
        "no_account": "Ninguna cuenta",
        "request": "Solicitar",
        "read_only": "Solo lectura",
        "empty_target_group": "Este grupo todav?a no contiene ning?n destino.",
        "no_target_group": "Ning?n grupo de destinos accesible",
        "no_target_group_help": (
            "Aqu? solo aparecen los grupos concedidos expl?citamente por una pol?tica activa."
        ),
        "view_requests": "Ver mis solicitudes",
        "privileged_access": "Acceso privilegiado",
        "requests_title": "Mis solicitudes.",
        "requests_intro": "Solicita un acceso cubierto por las pol?ticas de tus grupos.",
        "new_request": "Nueva solicitud",
        "justify_need": "Justifica tu necesidad",
        "send_request": "Enviar solicitud",
        "no_policy": "Ninguna pol?tica disponible",
        "no_policy_help": "Tu grupo debe recibir una pol?tica que permita solicitudes de acceso.",
        "history": "Historial",
        "request_singular": "solicitud",
        "no_request": "Ninguna solicitud",
        "request_history_help": "Tu historial aparecer? aqu?.",
        "profile": "Perfil",
        "personal_information": "Informaci?n personal",
        "save_profile": "Guardar perfil",
        "account_security": "Seguridad",
        "change_password": "Cambiar contrase?a",
        "save_password": "Actualizar contrase?a",
        "totp_authentication": "Autenticaci?n TOTP",
        "mfa_enabled": "MFA activada",
        "mfa_enabled_help": (
            "Se requiere un c?digo TOTP o de recuperaci?n en cada inicio de sesi?n."
        ),
        "last_use": "?ltimo uso",
        "never": "Nunca",
        "recovery_codes": "c?digos de recuperaci?n disponibles",
        "renew_recovery": "Renovar c?digos de recuperaci?n",
        "generate_recovery": "Generar nuevos c?digos",
        "reset_mfa": "Restablecer MFA",
        "reset_mfa_help": (
            "El dispositivo TOTP y todos los c?digos de recuperaci?n ser?n invalidados."
        ),
        "disable_mfa": "Desactivar MFA",
        "mfa_setup_help": "A?ade una segunda capa de protecci?n con tu aplicaci?n TOTP local.",
        "configure_totp": "Configurar TOTP",
    },
}


def ui_context(request):
    language = "fr"
    if getattr(request, "user", None) and request.user.is_authenticated:
        language = request.user.preferred_language
    else:
        language = request.session.get("preferred_language", "fr")
    return {"ui": TRANSLATIONS.get(language, TRANSLATIONS["en"]), "ui_language": language}
