TRANSLATIONS = {
    "fr": {
        "home": "Accueil",
        "passwords": "Mots de passe",
        "targets": "Cibles",
        "administration": "Administration",
        "my_account": "Mon compte",
        "logout": "Se déconnecter",
        "theme": "Changer de thème",
        "theme_system": "Auto",
        "theme_light": "Clair",
        "theme_dark": "Sombre",
        "language": "Langue",
        "personal_space": "Espace personnel",
        "hello": "Bonjour",
        "home_intro": (
            "Retrouvez rapidement vos coffres et les environnements auxquels vous avez accès."
        ),
        "platform_ok": "Plateforme opérationnelle",
        "vault_audit_available": "Coffre et audit disponibles",
        "requests": "Demandes",
        "pending": "en attente",
        "access": "Accès",
        "my_target_groups": "Mes groupes de cibles",
        "view_all": "Tout afficher",
        "activity": "Activité",
        "in_progress": "En cours",
        "no_group": "Aucun groupe accessible",
        "no_group_help": "Une politique doit relier l’un de vos groupes à un groupe de cibles.",
        "encrypted_vaults": "Coffres chiffrés",
        "password_page_title": "Mots de passe.",
        "password_page_intro": "Vos secrets personnels et les identifiants des cibles autorisées.",
        "add_secret": "Ajouter un secret",
        "create_group": "Créer un groupe",
        "save_vault": "Enregistrer dans mon coffre",
        "save_group": "Créer le groupe",
        "personal": "Personnel",
        "my_vault": "Mon coffre",
        "private_items": "Ces éléments ne sont visibles que par vous.",
        "ungrouped": "Sans groupe",
        "empty_vault": "Votre coffre est vide",
        "empty_vault_help": "Ajoutez un mot de passe, un TOTP, une carte ou une note sécurisée.",
        "reveal_audit": "Afficher et auditer",
        "business_justification": "Justification métier",
        "session_reason_placeholder": "Pourquoi cette session est-elle nécessaire ?",
        "reveal_reason_placeholder": "Pourquoi devez-vous consulter ce secret ?",
        "access_denied": "Accès refusé",
        "edit": "Modifier",
        "authorized_credentials": "Identifiants autorisés",
        "authorized_credentials_help": "Leur visibilité dépend de vos groupes et politiques.",
        "no_target_credentials": "Aucun identifiant de cible autorisé",
        "no_target_credentials_help": "Une politique doit autoriser l’action Consulter un secret.",
        "account_title": "Mon compte.",
        "account_intro": (
            "Modifiez votre profil, vos préférences, votre mot de passe et la protection MFA."
        ),
        "preferences": "Préférences",
        "appearance_language": "Apparence et langue",
        "save_preferences": "Enregistrer les préférences",
        "admin_overview": "Vue d’ensemble",
        "identities_rights": "Identités et droits",
        "users": "Utilisateurs",
        "user_groups": "Groupes utilisateurs",
        "roles_permissions": "Rôles et permissions",
        "ldap_directories": "Annuaires LDAP / AD",
        "oidc_providers": "Domaines de connexion",
        "group_mappings": "Correspondances de groupes",
        "target_groups": "Groupes de cibles",
        "ssh_rdp_equipment": "Équipements SSH / RDP",
        "domains": "Domaines",
        "ssh_host_keys": "Clés d’hôte SSH",
        "password_management": "Gestion des mots de passe",
        "target_credentials": "Identifiants des cibles",
        "rotation_policies": "Politiques de rotation",
        "rotations": "Rotations",
        "authorizations": "Autorisations",
        "access_policies": "Politiques d’accès",
        "time_frames": "Plages horaires",
        "current_approvals": "Approbations en cours",
        "monitoring_audit": "Surveillance et audit",
        "sessions": "Sessions",
        "audit_log": "Journal d’audit",
        "technical_admin": "Administration technique",
        "system": "Système",
        "session_policy": "Politique de session",
        "session_policy_intro": (
            "Déconnectez automatiquement les sessions web inactives ou trop anciennes."
        ),
        "enforced": "Appliquée côté serveur",
        "browser_sessions": "Sessions navigateur",
        "inactivity_and_absolute": "Inactivité et durée absolue",
        "save_policy": "Enregistrer la politique",
        "mfa_required_enabled": "MFA obligatoire activée",
        "mfa_required_enabled_detail": (
            "Tout utilisateur interactif doit confirmer un TOTP avant d’accéder aux "
            "secrets ou aux sessions privilégiées."
        ),
        "mfa_required_disabled": "Avertissement : MFA globale désactivée",
        "mfa_required_disabled_detail": (
            "Les comptes sans second facteur peuvent accéder à PAM-olive. Cette "
            "configuration réduit fortement la protection de la plateforme."
        ),
        "enforcement": "Application",
        "server_side_control": "Contrôle indépendant du navigateur",
        "session_policy_detail": (
            "Le délai est contrôlé sur chaque requête authentifiée. Fermer JavaScript ou "
            "modifier l’horloge du navigateur ne désactive pas la règle."
        ),
        "idle_limit": "Délai maximal sans activité",
        "absolute_limit": "Nouvelle authentification obligatoire",
        "control_title": "Pilotez PAM-olive.",
        "control_intro": (
            "Identités, mots de passe, cibles, approbations et traçabilité depuis une "
            "console unique."
        ),
        "connected_users": "Utilisateurs connectés",
        "active_sessions": "Sessions actives",
        "failed_logins": "Échecs de connexion (24 h)",
        "pending_approvals": "À approuver",
        "system_state": "État du système",
        "recent_failures": "Échecs récents",
        "database": "Base de données",
        "cache": "Cache",
        "operational": "Opérationnel",
        "no_recent_failure": "Aucun échec récent",
        "governed_console": "Console gouvernée",
        "groups_without_policy": "groupes sans politique",
        "groups_without_policy_help": "Ces groupes ne donnent encore aucun accès.",
        "targets_without_credential": "cibles sans identifiant",
        "targets_without_credential_help": (
            "Chaque cible devrait disposer d’au moins un identifiant."
        ),
        "configure": "Configurer",
        "fix": "Corriger",
        "web_sessions": "Sessions web",
        "authentication": "Authentification",
        "awaiting_decision": "En attente d’une décision",
        "live": "Temps réel",
        "now": "Maintenant",
        "error": "Erreur",
        "events_24h": "événements / 24 h",
        "security": "Sécurité",
        "multiple_groups_explicit_rights": "Groupes multiples, droits explicites",
        "deny_by_default": "Refus par défaut",
        "multi_group_help": "Un utilisateur peut appartenir à plusieurs groupes.",
        "capability_help": "Fonctions PAM et accès aux cibles.",
        "authorized_scopes_help": "Uniquement les périmètres autorisés.",
        "unknown": "Inconnu",
        "target_scopes": "Périmètres autorisés",
        "targets_page_title": "Cibles.",
        "targets_page_intro": (
            "Seuls les groupes de cibles accordés par vos politiques sont affichés."
        ),
        "my_requests": "Mes demandes",
        "authorized_target_group": "Groupe de cibles autorisé",
        "target_singular": "cible",
        "credential_singular": "identifiant",
        "open_session": "Ouvrir",
        "no_account": "Aucun compte",
        "request": "Demander",
        "read_only": "Consultation seule",
        "empty_target_group": "Ce groupe ne contient encore aucune cible.",
        "no_target_group": "Aucun groupe de cibles accessible",
        "no_target_group_help": (
            "Vous ne verrez ici que les groupes explicitement autorisés par une "
            "politique active."
        ),
        "view_requests": "Voir mes demandes",
        "privileged_access": "Accès privilégiés",
        "requests_title": "Mes demandes.",
        "requests_intro": "Demandez un accès couvert par les politiques de vos groupes.",
        "new_request": "Nouvelle demande",
        "justify_need": "Justifiez votre besoin",
        "send_request": "Envoyer la demande",
        "no_policy": "Aucune politique disponible",
        "no_policy_help": (
            "Votre groupe doit recevoir une politique autorisant les demandes d’accès."
        ),
        "history": "Historique",
        "request_singular": "demande",
        "no_request": "Aucune demande",
        "request_history_help": "Votre historique apparaîtra ici.",
        "profile": "Profil",
        "personal_information": "Informations personnelles",
        "save_profile": "Enregistrer le profil",
        "account_security": "Sécurité",
        "change_password": "Changer le mot de passe",
        "save_password": "Modifier le mot de passe",
        "totp_authentication": "Authentification TOTP",
        "mfa_enabled": "MFA activée",
        "mfa_enabled_help": (
            "Un code TOTP ou un code de récupération est demandé à chaque connexion."
        ),
        "last_use": "Dernière utilisation",
        "never": "Jamais",
        "recovery_codes": "codes disponibles",
        "renew_recovery": "Renouveler les codes de récupération",
        "generate_recovery": "Générer de nouveaux codes",
        "reset_mfa": "Réinitialiser la MFA",
        "reset_mfa_help": "L’appareil TOTP et tous les codes de récupération seront invalidés.",
        "disable_mfa": "Désactiver la MFA",
        "mfa_setup_help": "Ajoutez une seconde protection avec votre application TOTP locale.",
        "configure_totp": "Configurer le TOTP",
    },
    "en": {
        "home": "Home",
        "passwords": "Passwords",
        "targets": "Targets",
        "administration": "Administration",
        "my_account": "My account",
        "logout": "Sign out",
        "theme": "Switch theme",
        "theme_system": "Auto",
        "theme_light": "Light",
        "theme_dark": "Dark",
        "language": "Language",
        "personal_space": "Personal workspace",
        "hello": "Hello",
        "home_intro": "Quickly access your vaults and authorized environments.",
        "platform_ok": "Platform operational",
        "vault_audit_available": "Vault and audit available",
        "requests": "Requests",
        "pending": "pending",
        "access": "Access",
        "my_target_groups": "My target groups",
        "view_all": "View all",
        "activity": "Activity",
        "in_progress": "In progress",
        "no_group": "No accessible group",
        "no_group_help": "A policy must link one of your groups to a target group.",
        "encrypted_vaults": "Encrypted vaults",
        "password_page_title": "Passwords.",
        "password_page_intro": "Your personal secrets and authorized target credentials.",
        "add_secret": "Add a secret",
        "create_group": "Create a group",
        "save_vault": "Save to my vault",
        "save_group": "Create group",
        "personal": "Personal",
        "my_vault": "My vault",
        "private_items": "Only you can see these items.",
        "ungrouped": "Ungrouped",
        "empty_vault": "Your vault is empty",
        "empty_vault_help": "Add a password, TOTP, payment card, or secure note.",
        "reveal_audit": "Reveal and audit",
        "business_justification": "Business justification",
        "session_reason_placeholder": "Why is this session necessary?",
        "reveal_reason_placeholder": "Why do you need to reveal this secret?",
        "access_denied": "Access denied",
        "edit": "Edit",
        "authorized_credentials": "Authorized credentials",
        "authorized_credentials_help": "Visibility depends on your groups and policies.",
        "no_target_credentials": "No authorized target credentials",
        "no_target_credentials_help": "A policy must allow the View secret action.",
        "account_title": "My account.",
        "account_intro": "Update your profile, preferences, password, and MFA protection.",
        "preferences": "Preferences",
        "appearance_language": "Appearance and language",
        "save_preferences": "Save preferences",
        "admin_overview": "Overview",
        "identities_rights": "Identities and access",
        "users": "Users",
        "user_groups": "User groups",
        "roles_permissions": "Roles and permissions",
        "ldap_directories": "LDAP / AD directories",
        "oidc_providers": "Login domains",
        "group_mappings": "Group mappings",
        "target_groups": "Target groups",
        "ssh_rdp_equipment": "SSH / RDP equipment",
        "domains": "Domains",
        "ssh_host_keys": "SSH host keys",
        "password_management": "Password management",
        "target_credentials": "Target credentials",
        "rotation_policies": "Rotation policies",
        "rotations": "Rotations",
        "authorizations": "Authorizations",
        "access_policies": "Access policies",
        "time_frames": "Time frames",
        "current_approvals": "Pending approvals",
        "monitoring_audit": "Monitoring and audit",
        "sessions": "Sessions",
        "audit_log": "Audit log",
        "technical_admin": "Technical administration",
        "system": "System",
        "session_policy": "Session policy",
        "session_policy_intro": "Automatically disconnect inactive or overly old web sessions.",
        "enforced": "Server-side enforced",
        "browser_sessions": "Browser sessions",
        "inactivity_and_absolute": "Idle and absolute duration",
        "save_policy": "Save policy",
        "mfa_required_enabled": "Mandatory MFA enabled",
        "mfa_required_enabled_detail": (
            "Every interactive user must confirm a TOTP before accessing secrets or "
            "privileged sessions."
        ),
        "mfa_required_disabled": "Warning: global MFA disabled",
        "mfa_required_disabled_detail": (
            "Accounts without a second factor can access PAM-olive. This setting "
            "significantly weakens platform protection."
        ),
        "enforcement": "Enforcement",
        "server_side_control": "Browser-independent control",
        "session_policy_detail": (
            "The timeout is checked on every authenticated request. Disabling JavaScript or "
            "changing the browser clock cannot bypass it."
        ),
        "idle_limit": "Maximum idle period",
        "absolute_limit": "New authentication required",
        "control_title": "Control PAM-olive.",
        "control_intro": (
            "Manage identities, passwords, targets, approvals, and traceability from one "
            "console."
        ),
        "connected_users": "Connected users",
        "active_sessions": "Active sessions",
        "failed_logins": "Failed logins (24h)",
        "pending_approvals": "Pending approvals",
        "system_state": "System status",
        "recent_failures": "Recent failures",
        "database": "Database",
        "cache": "Cache",
        "operational": "Operational",
        "no_recent_failure": "No recent failure",
        "governed_console": "Governed console",
        "groups_without_policy": "groups without a policy",
        "groups_without_policy_help": "These groups do not grant access yet.",
        "targets_without_credential": "targets without a credential",
        "targets_without_credential_help": "Every target should have at least one credential.",
        "configure": "Configure",
        "fix": "Fix",
        "web_sessions": "Web sessions",
        "authentication": "Authentication",
        "awaiting_decision": "Awaiting a decision",
        "live": "Live",
        "now": "Now",
        "error": "Error",
        "events_24h": "events / 24h",
        "security": "Security",
        "multiple_groups_explicit_rights": "Multiple groups, explicit permissions",
        "deny_by_default": "Deny by default",
        "multi_group_help": "A user may belong to several groups.",
        "capability_help": "PAM capabilities and target access.",
        "authorized_scopes_help": "Only authorized scopes.",
        "unknown": "Unknown",
        "target_scopes": "Authorized scopes",
        "targets_page_title": "Targets.",
        "targets_page_intro": "Only target groups granted by your policies are displayed.",
        "my_requests": "My requests",
        "authorized_target_group": "Authorized target group",
        "target_singular": "target",
        "credential_singular": "credential",
        "open_session": "Open",
        "no_account": "No account",
        "request": "Request",
        "read_only": "Read only",
        "empty_target_group": "This group does not contain any target yet.",
        "no_target_group": "No accessible target group",
        "no_target_group_help": (
            "Only groups explicitly granted by an active policy are shown here."
        ),
        "view_requests": "View my requests",
        "privileged_access": "Privileged access",
        "requests_title": "My requests.",
        "requests_intro": "Request access covered by your groups’ policies.",
        "new_request": "New request",
        "justify_need": "Explain your need",
        "send_request": "Send request",
        "no_policy": "No policy available",
        "no_policy_help": "Your group must receive a policy allowing access requests.",
        "history": "History",
        "request_singular": "request",
        "no_request": "No request",
        "request_history_help": "Your history will appear here.",
        "profile": "Profile",
        "personal_information": "Personal information",
        "save_profile": "Save profile",
        "account_security": "Security",
        "change_password": "Change password",
        "save_password": "Update password",
        "totp_authentication": "TOTP authentication",
        "mfa_enabled": "MFA enabled",
        "mfa_enabled_help": "A TOTP or recovery code is required at each sign-in.",
        "last_use": "Last use",
        "never": "Never",
        "recovery_codes": "recovery codes available",
        "renew_recovery": "Renew recovery codes",
        "generate_recovery": "Generate new codes",
        "reset_mfa": "Reset MFA",
        "reset_mfa_help": "The TOTP device and all recovery codes will be invalidated.",
        "disable_mfa": "Disable MFA",
        "mfa_setup_help": "Add a second layer of protection with your local TOTP app.",
        "configure_totp": "Configure TOTP",
    },
    "es": {
        "home": "Inicio",
        "passwords": "Contraseñas",
        "targets": "Destinos",
        "administration": "Administración",
        "my_account": "Mi cuenta",
        "logout": "Cerrar sesión",
        "theme": "Cambiar tema",
        "theme_system": "Auto",
        "theme_light": "Claro",
        "theme_dark": "Oscuro",
        "language": "Idioma",
        "personal_space": "Espacio personal",
        "hello": "Hola",
        "home_intro": "Accede rápidamente a tus bóvedas y entornos autorizados.",
        "platform_ok": "Plataforma operativa",
        "vault_audit_available": "Bóveda y auditoría disponibles",
        "requests": "Solicitudes",
        "pending": "pendientes",
        "access": "Acceso",
        "my_target_groups": "Mis grupos de destinos",
        "view_all": "Ver todo",
        "activity": "Actividad",
        "in_progress": "En curso",
        "no_group": "Ningún grupo accesible",
        "no_group_help": "Una política debe vincular uno de tus grupos con un grupo de destinos.",
        "encrypted_vaults": "Bóvedas cifradas",
        "password_page_title": "Contraseñas.",
        "password_page_intro": "Tus secretos personales y credenciales de destino autorizadas.",
        "add_secret": "Añadir un secreto",
        "create_group": "Crear un grupo",
        "save_vault": "Guardar en mi bóveda",
        "save_group": "Crear grupo",
        "personal": "Personal",
        "my_vault": "Mi bóveda",
        "private_items": "Solo tú puedes ver estos elementos.",
        "ungrouped": "Sin grupo",
        "empty_vault": "Tu bóveda está vacía",
        "empty_vault_help": "Añade una contraseña, TOTP, tarjeta o nota segura.",
        "reveal_audit": "Mostrar y auditar",
        "business_justification": "Justificación empresarial",
        "session_reason_placeholder": "¿Por qué es necesaria esta sesión?",
        "reveal_reason_placeholder": "¿Por qué necesita consultar este secreto?",
        "access_denied": "Acceso denegado",
        "edit": "Editar",
        "authorized_credentials": "Credenciales autorizadas",
        "authorized_credentials_help": "La visibilidad depende de tus grupos y políticas.",
        "no_target_credentials": "No hay credenciales de destino autorizadas",
        "no_target_credentials_help": "Una política debe permitir la acción Ver secreto.",
        "account_title": "Mi cuenta.",
        "account_intro": "Actualiza tu perfil, preferencias, contraseña y protección MFA.",
        "preferences": "Preferencias",
        "appearance_language": "Apariencia e idioma",
        "save_preferences": "Guardar preferencias",
        "admin_overview": "Resumen",
        "identities_rights": "Identidades y accesos",
        "users": "Usuarios",
        "user_groups": "Grupos de usuarios",
        "roles_permissions": "Roles y permisos",
        "ldap_directories": "Directorios LDAP / AD",
        "oidc_providers": "Dominios de conexión",
        "group_mappings": "Mapeos de grupos",
        "target_groups": "Grupos de destinos",
        "ssh_rdp_equipment": "Equipos SSH / RDP",
        "domains": "Dominios",
        "ssh_host_keys": "Claves de host SSH",
        "password_management": "Gestión de contraseñas",
        "target_credentials": "Credenciales de destino",
        "rotation_policies": "Políticas de rotación",
        "rotations": "Rotaciones",
        "authorizations": "Autorizaciones",
        "access_policies": "Políticas de acceso",
        "time_frames": "Franjas horarias",
        "current_approvals": "Aprobaciones pendientes",
        "monitoring_audit": "Supervisión y auditoría",
        "sessions": "Sesiones",
        "audit_log": "Registro de auditoría",
        "technical_admin": "Administración técnica",
        "system": "Sistema",
        "session_policy": "Política de sesión",
        "session_policy_intro": (
            "Desconecta automáticamente las sesiones web inactivas o demasiado antiguas."
        ),
        "enforced": "Aplicada en el servidor",
        "browser_sessions": "Sesiones del navegador",
        "inactivity_and_absolute": "Inactividad y duración absoluta",
        "save_policy": "Guardar política",
        "mfa_required_enabled": "MFA obligatoria activada",
        "mfa_required_enabled_detail": (
            "Cada usuario interactivo debe confirmar un TOTP antes de acceder a secretos "
            "o sesiones privilegiadas."
        ),
        "mfa_required_disabled": "Advertencia: MFA global desactivada",
        "mfa_required_disabled_detail": (
            "Las cuentas sin segundo factor pueden acceder a PAM-olive. Esta configuración "
            "reduce considerablemente la protección de la plataforma."
        ),
        "enforcement": "Aplicación",
        "server_side_control": "Control independiente del navegador",
        "session_policy_detail": (
            "El tiempo se verifica en cada solicitud autenticada. Desactivar JavaScript o "
            "cambiar el reloj del navegador no permite evitarlo."
        ),
        "idle_limit": "Periodo máximo de inactividad",
        "absolute_limit": "Nueva autenticación obligatoria",
        "control_title": "Controla PAM-olive.",
        "control_intro": (
            "Gestiona identidades, contraseñas, destinos, aprobaciones y trazabilidad desde "
            "una consola."
        ),
        "connected_users": "Usuarios conectados",
        "active_sessions": "Sesiones activas",
        "failed_logins": "Inicios fallidos (24 h)",
        "pending_approvals": "Aprobaciones pendientes",
        "system_state": "Estado del sistema",
        "recent_failures": "Fallos recientes",
        "database": "Base de datos",
        "cache": "Caché",
        "operational": "Operativo",
        "no_recent_failure": "Ningún fallo reciente",
        "governed_console": "Consola gobernada",
        "groups_without_policy": "grupos sin política",
        "groups_without_policy_help": "Estos grupos todavía no conceden acceso.",
        "targets_without_credential": "destinos sin credenciales",
        "targets_without_credential_help": "Cada destino debería tener al menos una credencial.",
        "configure": "Configurar",
        "fix": "Corregir",
        "web_sessions": "Sesiones web",
        "authentication": "Autenticación",
        "awaiting_decision": "Esperando una decisión",
        "live": "En directo",
        "now": "Ahora",
        "error": "Error",
        "events_24h": "eventos / 24 h",
        "security": "Seguridad",
        "multiple_groups_explicit_rights": "Múltiples grupos, permisos explícitos",
        "deny_by_default": "Denegar por defecto",
        "multi_group_help": "Un usuario puede pertenecer a varios grupos.",
        "capability_help": "Funciones PAM y acceso a destinos.",
        "authorized_scopes_help": "Solo ámbitos autorizados.",
        "unknown": "Desconocido",
        "target_scopes": "Ámbitos autorizados",
        "targets_page_title": "Destinos.",
        "targets_page_intro": (
            "Solo se muestran los grupos de destinos concedidos por tus políticas."
        ),
        "my_requests": "Mis solicitudes",
        "authorized_target_group": "Grupo de destinos autorizado",
        "target_singular": "destino",
        "credential_singular": "credencial",
        "open_session": "Abrir",
        "no_account": "Ninguna cuenta",
        "request": "Solicitar",
        "read_only": "Solo lectura",
        "empty_target_group": "Este grupo todavía no contiene ningún destino.",
        "no_target_group": "Ningún grupo de destinos accesible",
        "no_target_group_help": (
            "Aquí solo aparecen los grupos concedidos explícitamente por una política activa."
        ),
        "view_requests": "Ver mis solicitudes",
        "privileged_access": "Acceso privilegiado",
        "requests_title": "Mis solicitudes.",
        "requests_intro": "Solicita un acceso cubierto por las políticas de tus grupos.",
        "new_request": "Nueva solicitud",
        "justify_need": "Justifica tu necesidad",
        "send_request": "Enviar solicitud",
        "no_policy": "Ninguna política disponible",
        "no_policy_help": "Tu grupo debe recibir una política que permita solicitudes de acceso.",
        "history": "Historial",
        "request_singular": "solicitud",
        "no_request": "Ninguna solicitud",
        "request_history_help": "Tu historial aparecerá aquí.",
        "profile": "Perfil",
        "personal_information": "Información personal",
        "save_profile": "Guardar perfil",
        "account_security": "Seguridad",
        "change_password": "Cambiar contraseña",
        "save_password": "Actualizar contraseña",
        "totp_authentication": "Autenticación TOTP",
        "mfa_enabled": "MFA activada",
        "mfa_enabled_help": (
            "Se requiere un código TOTP o de recuperación en cada inicio de sesión."
        ),
        "last_use": "Último uso",
        "never": "Nunca",
        "recovery_codes": "códigos de recuperación disponibles",
        "renew_recovery": "Renovar códigos de recuperación",
        "generate_recovery": "Generar nuevos códigos",
        "reset_mfa": "Restablecer MFA",
        "reset_mfa_help": (
            "El dispositivo TOTP y todos los códigos de recuperación serán invalidados."
        ),
        "disable_mfa": "Desactivar MFA",
        "mfa_setup_help": "Añade una segunda capa de protección con tu aplicación TOTP local.",
        "configure_totp": "Configurar TOTP",
    },
}


def ui_context(request):
    language = "fr"
    if getattr(request, "user", None) and request.user.is_authenticated:
        language = request.user.preferred_language
    else:
        language = request.session.get("preferred_language", "fr")
    return {"ui": TRANSLATIONS.get(language, TRANSLATIONS["en"]), "ui_language": language}
