# Generated by Django 5.2.16 on 2026-07-13 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('policies', '0001_initial'),
        ('rbac', '0001_initial'),
        ('targets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesspolicy',
            name='roles',
            field=models.ManyToManyField(blank=True, to='rbac.role'),
        ),
        migrations.AddField(
            model_name='accesspolicy',
            name='targets',
            field=models.ManyToManyField(related_name='policies', to='targets.target'),
        ),
    ]
