# Generated by Django 5.2.16 on 2026-07-13 20:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0004_accesspolicy_approval_quorum_and_more'),
        ('vault', '0005_secretlease'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesspolicy',
            name='access_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accesspolicy',
            name='access_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accesspolicy',
            name='credentials',
            field=models.ManyToManyField(blank=True, related_name='access_policies', to='vault.credential'),
        ),
        migrations.AddField(
            model_name='accesspolicy',
            name='max_concurrent_sessions',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)]),
        ),
        migrations.AddField(
            model_name='accesspolicy',
            name='protocols',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='accesspolicy',
            name='source_cidrs',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='accesspolicy',
            name='valid_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accesspolicy',
            name='valid_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accesspolicy',
            name='weekdays',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
