# Generated by Django 5.2.16 on 2026-07-15 19:54

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0006_accesspolicy_rdp_clipboard_controls'),
        ('targets', '0005_target_rdp_security_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeFrame',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('weekdays', models.JSONField(blank=True, default=list)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('enabled', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SecretRotationPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('strategy', models.CharField(choices=[('generated_password', 'Mot de passe généré')], default='generated_password', max_length=32)),
                ('interval_days', models.PositiveIntegerField(default=30, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3650)])),
                ('password_length', models.PositiveSmallIntegerField(default=32, validators=[django.core.validators.MinValueValidator(16), django.core.validators.MaxValueValidator(128)])),
                ('connector_key', models.CharField(blank=True, max_length=100)),
                ('enabled', models.BooleanField(default=True)),
                ('target_groups', models.ManyToManyField(blank=True, related_name='rotation_policies', to='targets.targetgroup')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='accesspolicy',
            name='time_frames',
            field=models.ManyToManyField(blank=True, related_name='access_policies', to='policies.timeframe'),
        ),
    ]
