# Generated by Django 5.2.16 on 2026-07-15 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='preferred_language',
            field=models.CharField(choices=[('en', 'English'), ('fr', 'Français'), ('es', 'Español')], default='fr', max_length=5),
        ),
        migrations.AddField(
            model_name='user',
            name='preferred_theme',
            field=models.CharField(choices=[('dark', 'Dark'), ('light', 'Light'), ('system', 'System')], default='dark', max_length=10),
        ),
    ]
