# Generated by Django 5.2.16 on 2026-07-13 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credential',
            name='kind',
            field=models.CharField(choices=[('password', 'Password'), ('ssh_key', 'SSH private key'), ('totp', 'TOTP seed')], max_length=20),
        ),
    ]
