# Generated by Django 5.2.16 on 2026-07-13 18:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0002_alter_credential_kind'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='credential',
            name='encrypted_totp_secret',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PersonalVaultItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=180)),
                ('item_type', models.CharField(choices=[('login', 'Identifiant'), ('totp', 'TOTP'), ('card', 'Carte bancaire'), ('note', 'Note sécurisée')], max_length=20)),
                ('encrypted_payload', models.BinaryField()),
                ('favorite', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_vault_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-favorite', 'name'),
            },
        ),
    ]
