# Generated by Django 5.2.16 on 2026-07-13 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0003_domain_target_description_target_kind_and_more'),
        ('vault', '0003_credential_encrypted_totp_secret_personalvaultitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='credential',
            name='account_type',
            field=models.CharField(choices=[('local', 'Compte local'), ('domain', 'Compte de domaine'), ('service', 'Compte de service'), ('application', 'Compte d’application')], default='local', max_length=20),
        ),
        migrations.AddField(
            model_name='credential',
            name='checkout_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='credential',
            name='domain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='credentials', to='targets.domain'),
        ),
        migrations.AddField(
            model_name='credential',
            name='last_checked_out_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='credential',
            name='rotation_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='credential',
            name='rotation_interval_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
