# Generated by Django 5.2.16 on 2026-07-13 19:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0003_accessrequest_ticket_reference_approvaldecision'),
        ('policies', '0004_accesspolicy_approval_quorum_and_more'),
        ('vault', '0004_credential_account_type_credential_checkout_enabled_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecretLease',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purpose', models.CharField(choices=[('reveal', 'Consultation interactive'), ('session', 'Ouverture de session'), ('rotation', 'Rotation')], max_length=20)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('max_uses', models.PositiveSmallIntegerField(default=1)),
                ('use_count', models.PositiveSmallIntegerField(default=0)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('access_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='secret_leases', to='approvals.accessrequest')),
                ('credential', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leases', to='vault.credential')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='policies.accesspolicy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='secret_leases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
