# Generated by Django 5.2.16 on 2026-07-15 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0007_timeframe_secretrotationpolicy_and_more'),
        ('vault', '0007_encryption_key_identifiers'),
    ]

    operations = [
        migrations.AddField(
            model_name='credential',
            name='rotation_policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='credentials', to='policies.secretrotationpolicy'),
        ),
    ]
