# Generated by Django 5.2.16 on 2026-07-13 19:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0002_targetgroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('kind', models.CharField(choices=[('local', 'Domaine local'), ('active_directory', 'Microsoft Active Directory')], default='local', max_length=30)),
                ('dns_name', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('enabled', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='target',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='target',
            name='kind',
            field=models.CharField(choices=[('device', 'Équipement'), ('application', 'Application'), ('web_application', 'Application web')], default='device', max_length=30),
        ),
        migrations.AddField(
            model_name='target',
            name='platform',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='target',
            name='protocol',
            field=models.CharField(choices=[('ssh', 'SSH'), ('rdp', 'RDP'), ('web', 'HTTPS / Web'), ('vnc', 'VNC'), ('telnet', 'TELNET'), ('raw_tcp', 'TCP brut')], max_length=16),
        ),
        migrations.AddField(
            model_name='target',
            name='domain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='targets', to='targets.domain'),
        ),
    ]
