# Generated by Django 5.2.16 on 2026-07-13 20:06

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0003_domain_target_description_target_kind_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TargetHostKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key_type', models.CharField(editable=False, max_length=64)),
                ('public_key', models.TextField()),
                ('fingerprint_sha256', models.CharField(editable=False, max_length=100)),
                ('comment', models.CharField(blank=True, max_length=255)),
                ('trusted_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('revoked_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='revoked_target_host_keys', to=settings.AUTH_USER_MODEL)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='host_keys', to='targets.target')),
                ('trusted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trusted_target_host_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('target', 'fingerprint_sha256'), name='unique_target_host_key_fingerprint')],
            },
        ),
    ]
