# Generated by Django 5.2.16 on 2026-07-15 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0005_target_rdp_security_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='ssh_host_key_policy',
            field=models.CharField(choices=[('tofu', 'Trust on first use'), ('strict', 'Require prior administrator approval')], default='tofu', max_length=16),
        ),
    ]
