# Generated by Django 5.2.16 on 2026-07-13 19:18

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectors', '0001_initial'),
        ('rbac', '0005_roleassignment_assigned_by_roleassignment_reason_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentitySource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('kind', models.CharField(choices=[('ldap', 'LDAP'), ('active_directory', 'Microsoft Active Directory'), ('oidc', 'OpenID Connect')], max_length=30)),
                ('enabled', models.BooleanField(default=False)),
                ('verify_tls', models.BooleanField(default=True)),
                ('encrypted_configuration', models.BinaryField()),
                ('sync_enabled', models.BooleanField(default=False)),
                ('sync_interval_minutes', models.PositiveIntegerField(default=60, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(10080)])),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_sync_status', models.CharField(choices=[('never', 'Jamais synchronisé'), ('running', 'Synchronisation en cours'), ('success', 'Synchronisation réussie'), ('failed', 'Synchronisation en échec')], default='never', max_length=20)),
                ('last_error', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExternalIdentity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.CharField(max_length=512)),
                ('username', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('claims', models.JSONField(blank=True, default=dict)),
                ('enabled', models.BooleanField(default=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_identities', to=settings.AUTH_USER_MODEL)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='external_identities', to='connectors.identitysource')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('source', 'subject'), name='unique_external_identity_subject'), models.UniqueConstraint(fields=('source', 'user'), name='unique_external_identity_user')],
            },
        ),
        migrations.CreateModel(
            name='DirectoryGroupMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_group', models.CharField(max_length=512)),
                ('auto_create_users', models.BooleanField(default=True)),
                ('enabled', models.BooleanField(default=True)),
                ('user_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='directory_mappings', to='rbac.usergroup')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_mappings', to='connectors.identitysource')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('source', 'external_group'), name='unique_directory_group_mapping')],
            },
        ),
    ]
