# Generated by Django 5.2.16 on 2026-07-13 19:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectors', '0002_identitysource_externalidentity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalGroupMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('preserve_membership_on_unlink', models.BooleanField(default=False)),
                ('identity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managed_group_memberships', to='connectors.externalidentity')),
                ('mapping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managed_memberships', to='connectors.directorygroupmapping')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('identity', 'mapping'), name='unique_external_group_membership')],
            },
        ),
    ]
