# Generated by Django 5.2.16 on 2026-07-13 19:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='accessrequest',
            name='ticket_reference',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='ApprovalDecision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('decision', models.CharField(choices=[('approve', 'Approuver'), ('reject', 'Refuser')], max_length=10)),
                ('comment', models.TextField(blank=True)),
                ('access_request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='decisions', to='approvals.accessrequest')),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approval_decisions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created_at',),
                'constraints': [models.UniqueConstraint(fields=('access_request', 'approver'), name='unique_approval_decision_per_approver')],
            },
        ),
    ]
